### PR TITLE
reworking api

### PR DESCRIPTION
**Pull request by rmannibucau**
Some proposal (not mergeable I think)

Idea is to base the SPI on the builder and have a Factory as static facade for the user

Also removed the ordinal since the builder takes sorted sources, still need to find a way to sort automatic loading (there is a TODO) but I'd like the ordinal to be external to the source itself, maybe sthg like:

```
SourceConfiguration { source; ordinal }
```

and we would load it instead of loading ConfigSource

That said the SPI design is in this PR and the clean up of list method too

### CODE REVIEW

**Comment by struberg** [comment]
There are a few things which came up quite a few times, let me go through them.
Let's start with the first:

* @Priority instead of oridinal. That's a very tempting change. And we tried that a few times. But always failed. Why? Because the ordinal might be different. 
Think about writing a PropertyfileConfigSource implements ConfigSource which just takes the URL. There is only ONE single PropertyfileConfigSource, so it can only have one single @Priority. No way to change that. That means you loose the ability to change the ordinal based on single ConfigSource instances. You would need a new class for each of them. But since the number of property files is totally dynamic, this simply won't work.

**Comment by rmannibucau** [comment]
that's why I propose SourceConfiguration  and @Priority would just be one automatic case of that

**Comment by struberg** [comment]
* ConfigSource#getProperties() We really need that. You have to give the user a way to iterate over all properties to enlist them on e.g. an admin page. That was the reason why we added them. 
Think about providing a admin page in the TomEE gui (or JBoss etc) where Ops can look at to check what effective values they got for the application. 
I've seen that MANY times that we had some weirdly behaving server, just to later find out that some webservice client talks to the wrong endpoint.

**Comment by r-tt** [comment]
getProperties is not needed exactly for the reason you mention

1. we should have a ListableConfiguration on top of configuration if so (with ListableConfigSource and if any source is not listable it fails)
2. we should list keys only (think to aggregating remote sources) and only expose getproperties is fully working (see 1)

**Comment by struberg** [comment]
manually applied as it had too many conflicts.

**Pull request closed without merging**
